#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ ff
Scrape the Fest & Flauschig podcast
EOF
  exit
fi

TMP=$(mktemp)
curl -Ss "https://open.spotify.com/show/1OLcQdw2PFDPG1jo3s0wbp" |
  grep -Po '{.*?:episode:.*?}' | sed 's|&amp;|\&|g' | awk -F\; '{ print $1"," }' | sed '$ s/,$//' >>$TMP
printf "]}}" >>$TMP

echo $TMP
